name: riverui-dev

services:
  postgres:
    image: "postgres:18.6-alpine@sha256:77f585114c32fbca283dc835b0596f4e52b51b4c6662d7810b2f4084f60a1873"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "river_dev", "-U", "postgres"]
      timeout: 20s
      retries: 10
      start_period: 3s
    volumes:
      - ./scripts/docker-compose-dev/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  migrate:
    image: "golang:1.27.1-alpine@sha256:8a5910f31396cd4d89662f56c68b3ae31d374308270a1c3bd96672ee5ed43414"
    depends_on:
      postgres:
        condition: "service_healthy"
    entrypoint: "/bin/sh"
    # cache the go binaries so they don't redownload
    volumes:
      - gopath:/go
    command:
      - -c
      - |
        echo "downloading river binary"
        go install github.com/riverqueue/river/cmd/river@latest
        echo "migrating river_dev database"
        river migrate-up --database-url "postgres://postgres:postgres@postgres/river_dev"
        echo "migrating river_test database"
        river migrate-up --database-url "postgres://postgres:postgres@postgres/river_test"
volumes:
  gopath:
