name: riverui-dev

services:
  postgres:
    image: "postgres:18.4-alpine@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "river_dev", "-U", "postgres"]
      timeout: 20s
      retries: 10
      start_period: 3s
    volumes:
      - ./scripts/docker-compose-dev/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  migrate:
    image: "golang:1.27.0-alpine@sha256:4c9fe60190a2a3350ddc51de80d0224b8a6698d12bdfc999fee45ea9d6c46dbc"
    depends_on:
      postgres:
        condition: "service_healthy"
    entrypoint: "/bin/sh"
    # cache the go binaries so they don't redownload
    volumes:
      - gopath:/go
    command:
      - -c
      - |
        echo "downloading river binary"
        go install github.com/riverqueue/river/cmd/river@latest
        echo "migrating river_dev database"
        river migrate-up --database-url "postgres://postgres:postgres@postgres/river_dev"
        echo "migrating river_test database"
        river migrate-up --database-url "postgres://postgres:postgres@postgres/river_test"
volumes:
  gopath:
