// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: river_job.sql

package dbsqlc

import (
	"context"
	"time"
)

const jobCountAnalyzedAt = `-- name: JobCountAnalyzedAt :one
SELECT GREATEST(last_analyze, last_autoanalyze)::timestamptz AS analyzed_at
FROM pg_stat_all_tables
WHERE schemaname = COALESCE(NULLIF($1::text, ''), current_schema())
  AND relname = 'river_job'
`

func (q *Queries) JobCountAnalyzedAt(ctx context.Context, db DBTX, schema string) (time.Time, error) {
	row := db.QueryRow(ctx, jobCountAnalyzedAt, schema)
	var analyzed_at time.Time
	err := row.Scan(&analyzed_at)
	return analyzed_at, err
}

const jobCountByAllStatesCapped = `-- name: JobCountByAllStatesCapped :one
SELECT
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'available' ORDER BY queue, priority, scheduled_at, id LIMIT $1::int) AS limited_available) AS available,
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'cancelled' ORDER BY queue, priority, scheduled_at, id LIMIT $1::int) AS limited_cancelled) AS cancelled,
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'completed' ORDER BY queue, priority, scheduled_at, id LIMIT $1::int) AS limited_completed) AS completed,
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'discarded' ORDER BY queue, priority, scheduled_at, id LIMIT $1::int) AS limited_discarded) AS discarded,
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'pending' ORDER BY queue, priority, scheduled_at, id LIMIT $1::int) AS limited_pending) AS pending,
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'retryable' ORDER BY queue, priority, scheduled_at, id LIMIT $1::int) AS limited_retryable) AS retryable,
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'running' ORDER BY queue, priority, scheduled_at, id LIMIT $1::int) AS limited_running) AS running,
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'scheduled' ORDER BY queue, priority, scheduled_at, id LIMIT $1::int) AS limited_scheduled) AS scheduled
`

type JobCountByAllStatesCappedRow struct {
	Available int64
	Cancelled int64
	Completed int64
	Discarded int64
	Pending   int64
	Retryable int64
	Running   int64
	Scheduled int64
}

// Each subquery follows the remaining columns of River's prioritized fetching
// index so the database can stop its index scan as soon as the limit is met.
func (q *Queries) JobCountByAllStatesCapped(ctx context.Context, db DBTX, max int32) (*JobCountByAllStatesCappedRow, error) {
	row := db.QueryRow(ctx, jobCountByAllStatesCapped, max)
	var i JobCountByAllStatesCappedRow
	err := row.Scan(
		&i.Available,
		&i.Cancelled,
		&i.Completed,
		&i.Discarded,
		&i.Pending,
		&i.Retryable,
		&i.Running,
		&i.Scheduled,
	)
	return &i, err
}

const jobCountEstimateAvailable = `-- name: JobCountEstimateAvailable :one

EXPLAIN (FORMAT JSON) SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'available'
`

type JobCountEstimateAvailableRow struct {
}

// These queries intentionally embed a state literal. A parameterized query can
// eventually receive PostgreSQL's generic prepared plan, which loses the
// per-state selectivity that makes the estimate useful.
func (q *Queries) JobCountEstimateAvailable(ctx context.Context, db DBTX) (*JobCountEstimateAvailableRow, error) {
	row := db.QueryRow(ctx, jobCountEstimateAvailable)
	var i JobCountEstimateAvailableRow
	err := row.Scan()
	return &i, err
}

const jobCountEstimateCancelled = `-- name: JobCountEstimateCancelled :one
EXPLAIN (FORMAT JSON) SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'cancelled'
`

type JobCountEstimateCancelledRow struct {
}

func (q *Queries) JobCountEstimateCancelled(ctx context.Context, db DBTX) (*JobCountEstimateCancelledRow, error) {
	row := db.QueryRow(ctx, jobCountEstimateCancelled)
	var i JobCountEstimateCancelledRow
	err := row.Scan()
	return &i, err
}

const jobCountEstimateCompleted = `-- name: JobCountEstimateCompleted :one
EXPLAIN (FORMAT JSON) SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'completed'
`

type JobCountEstimateCompletedRow struct {
}

func (q *Queries) JobCountEstimateCompleted(ctx context.Context, db DBTX) (*JobCountEstimateCompletedRow, error) {
	row := db.QueryRow(ctx, jobCountEstimateCompleted)
	var i JobCountEstimateCompletedRow
	err := row.Scan()
	return &i, err
}

const jobCountEstimateDiscarded = `-- name: JobCountEstimateDiscarded :one
EXPLAIN (FORMAT JSON) SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'discarded'
`

type JobCountEstimateDiscardedRow struct {
}

func (q *Queries) JobCountEstimateDiscarded(ctx context.Context, db DBTX) (*JobCountEstimateDiscardedRow, error) {
	row := db.QueryRow(ctx, jobCountEstimateDiscarded)
	var i JobCountEstimateDiscardedRow
	err := row.Scan()
	return &i, err
}

const jobCountEstimatePending = `-- name: JobCountEstimatePending :one
EXPLAIN (FORMAT JSON) SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'pending'
`

type JobCountEstimatePendingRow struct {
}

func (q *Queries) JobCountEstimatePending(ctx context.Context, db DBTX) (*JobCountEstimatePendingRow, error) {
	row := db.QueryRow(ctx, jobCountEstimatePending)
	var i JobCountEstimatePendingRow
	err := row.Scan()
	return &i, err
}

const jobCountEstimateRetryable = `-- name: JobCountEstimateRetryable :one
EXPLAIN (FORMAT JSON) SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'retryable'
`

type JobCountEstimateRetryableRow struct {
}

func (q *Queries) JobCountEstimateRetryable(ctx context.Context, db DBTX) (*JobCountEstimateRetryableRow, error) {
	row := db.QueryRow(ctx, jobCountEstimateRetryable)
	var i JobCountEstimateRetryableRow
	err := row.Scan()
	return &i, err
}

const jobCountEstimateRunning = `-- name: JobCountEstimateRunning :one
EXPLAIN (FORMAT JSON) SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'running'
`

type JobCountEstimateRunningRow struct {
}

func (q *Queries) JobCountEstimateRunning(ctx context.Context, db DBTX) (*JobCountEstimateRunningRow, error) {
	row := db.QueryRow(ctx, jobCountEstimateRunning)
	var i JobCountEstimateRunningRow
	err := row.Scan()
	return &i, err
}

const jobCountEstimateScheduled = `-- name: JobCountEstimateScheduled :one
EXPLAIN (FORMAT JSON) SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'scheduled'
`

type JobCountEstimateScheduledRow struct {
}

func (q *Queries) JobCountEstimateScheduled(ctx context.Context, db DBTX) (*JobCountEstimateScheduledRow, error) {
	row := db.QueryRow(ctx, jobCountEstimateScheduled)
	var i JobCountEstimateScheduledRow
	err := row.Scan()
	return &i, err
}
