// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package dbsqlc

import (
	"time"
)

type RiverJob struct {
	ID          int64
	Priority    int64
	Queue       string
	State       string
	ScheduledAt time.Time
}

type SqliteStat4 struct {
	Tbl    string
	Idx    string
	Neq    string
	Nlt    string
	Ndlt   string
	Sample []byte
}
