// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: river_job.sql

package dbsqlc

import (
	"context"
)

const jobCountByAllStatesCapped = `-- name: JobCountByAllStatesCapped :one
SELECT
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'available' ORDER BY queue, priority, scheduled_at, id LIMIT ?1) AS limited_available) AS available,
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'cancelled' ORDER BY queue, priority, scheduled_at, id LIMIT ?1) AS limited_cancelled) AS cancelled,
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'completed' ORDER BY queue, priority, scheduled_at, id LIMIT ?1) AS limited_completed) AS completed,
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'discarded' ORDER BY queue, priority, scheduled_at, id LIMIT ?1) AS limited_discarded) AS discarded,
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'pending' ORDER BY queue, priority, scheduled_at, id LIMIT ?1) AS limited_pending) AS pending,
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'retryable' ORDER BY queue, priority, scheduled_at, id LIMIT ?1) AS limited_retryable) AS retryable,
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'running' ORDER BY queue, priority, scheduled_at, id LIMIT ?1) AS limited_running) AS running,
    (SELECT count(*) FROM (SELECT 1 FROM /* TEMPLATE: schema */river_job WHERE state = 'scheduled' ORDER BY queue, priority, scheduled_at, id LIMIT ?1) AS limited_scheduled) AS scheduled
`

type JobCountByAllStatesCappedRow struct {
	Available int64
	Cancelled int64
	Completed int64
	Discarded int64
	Pending   int64
	Retryable int64
	Running   int64
	Scheduled int64
}

// Each subquery follows the remaining columns of River's prioritized fetching
// index so the database can stop its index scan as soon as the limit is met.
func (q *Queries) JobCountByAllStatesCapped(ctx context.Context, db DBTX, max int64) (*JobCountByAllStatesCappedRow, error) {
	row := db.QueryRowContext(ctx, jobCountByAllStatesCapped, max)
	var i JobCountByAllStatesCappedRow
	err := row.Scan(
		&i.Available,
		&i.Cancelled,
		&i.Completed,
		&i.Discarded,
		&i.Pending,
		&i.Retryable,
		&i.Running,
		&i.Scheduled,
	)
	return &i, err
}
