// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
)

const jobCountByQueueAndState = `-- name: JobCountByQueueAndState :many
WITH all_queues AS (
  SELECT unnest($1::text[])::text AS queue
),

running_job_counts AS (
  SELECT
    queue,
    COUNT(*) AS count
  FROM
    river_job
  WHERE
    queue = ANY($1::text[]) AND
    state = 'running'
  GROUP BY queue
),

available_job_counts AS (
  SELECT
    queue,
    COUNT(*) AS count
  FROM
    river_job
  WHERE
    queue = ANY($1::text[]) AND
    state = 'available'
  GROUP BY queue
)

SELECT
    all_queues.queue,
    COALESCE(available_job_counts.count, 0) AS available_jobs_count,
    COALESCE(running_job_counts.count, 0) AS running_jobs_count
FROM
    all_queues
LEFT JOIN
    running_job_counts ON all_queues.queue = running_job_counts.queue
LEFT JOIN
    available_job_counts ON all_queues.queue = available_job_counts.queue
`

type JobCountByQueueAndStateRow struct {
	Queue              string
	AvailableJobsCount int64
	RunningJobsCount   int64
}

func (q *Queries) JobCountByQueueAndState(ctx context.Context, queueNames []string) ([]JobCountByQueueAndStateRow, error) {
	rows, err := q.db.Query(ctx, jobCountByQueueAndState, queueNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobCountByQueueAndStateRow
	for rows.Next() {
		var i JobCountByQueueAndStateRow
		if err := rows.Scan(&i.Queue, &i.AvailableJobsCount, &i.RunningJobsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobCountByState = `-- name: JobCountByState :many
SELECT
  state,
  count(*)
FROM
  river_job
WHERE
  queue IS NOT NULL AND
  priority > 0 AND
  scheduled_at IS NOT NULL AND
  id IS NOT NULL
GROUP BY state
`

type JobCountByStateRow struct {
	State RiverJobState
	Count int64
}

func (q *Queries) JobCountByState(ctx context.Context) ([]JobCountByStateRow, error) {
	rows, err := q.db.Query(ctx, jobCountByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobCountByStateRow
	for rows.Next() {
		var i JobCountByStateRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobListWorkflow = `-- name: JobListWorkflow :many
SELECT
  id, state, attempt, max_attempts, attempted_at, created_at, finalized_at, scheduled_at, priority, args, attempted_by, errors, kind, metadata, queue, tags
FROM
  river_job
WHERE
  metadata @> jsonb_build_object('workflow_id', $1::text)
ORDER BY
  kind = $2::text DESC,
  id ASC
LIMIT $4::integer
OFFSET $3::bigint
`

type JobListWorkflowParams struct {
	WorkflowID             string
	WorkflowSupervisorKind string
	PaginationOffset       int64
	PaginationLimit        int32
}

func (q *Queries) JobListWorkflow(ctx context.Context, arg JobListWorkflowParams) ([]RiverJob, error) {
	rows, err := q.db.Query(ctx, jobListWorkflow,
		arg.WorkflowID,
		arg.WorkflowSupervisorKind,
		arg.PaginationOffset,
		arg.PaginationLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RiverJob
	for rows.Next() {
		var i RiverJob
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.Attempt,
			&i.MaxAttempts,
			&i.AttemptedAt,
			&i.CreatedAt,
			&i.FinalizedAt,
			&i.ScheduledAt,
			&i.Priority,
			&i.Args,
			&i.AttemptedBy,
			&i.Errors,
			&i.Kind,
			&i.Metadata,
			&i.Queue,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
