name: Docker

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      ref:
        description: "Tag to build (e.g. v0.1.0)"
        required: true

env:
  ECR_REGION: us-east-2

jobs:
  build-riverui:
    name: "Build image: riverui"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}
      REGISTRY: ghcr.io
    strategy:
      matrix:
        docker_platform:
          - linux/amd64
          - linux/arm64
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Prepare
        run: |
          platform=${{ matrix.docker_platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.source=https://github.com/riverqueue/riverui
            org.opencontainers.image.description="River UI is a web-based user interface for River, a fast and reliable background job system."
            org.opencontainers.image.licenses=MPL-2.0
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build and push to GitHub Container Registry
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          pull: true
          platforms: ${{ matrix.docker_platform }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache,mode=max
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true,annotation-index.org.opencontainers.image.description=River UI

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          push-to-registry: true
          subject-digest: ${{ steps.build.outputs.digest }}
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-oss-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  build-riverproui:
    name: "Build image: riverproui"
    runs-on: ubuntu-latest
    env:
      ECR_ACCOUNT_ID: ${{ secrets.ECR_CACHE_AWS_ACCOUNT_ID }}
      ECR_ROLE_ARN: ${{ secrets.ECR_CACHE_ROLE_ARN }}
    strategy:
      matrix:
        docker_platform:
          - linux/amd64
          - linux/arm64
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ECR_ROLE_ARN }}
          aws-region: ${{ env.ECR_REGION }}
          role-session-name: GitHubActions

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.ECR_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com

      - name: Prepare
        run: |
          platform=${{ matrix.docker_platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Set TAG
        run: echo "TAG=${{ inputs.ref || github.ref_name }}" >> $GITHUB_ENV

      - name: Validate TAG
        if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
        run: |
          if [[ ! "$TAG" == v* ]]; then
            echo "Tag must start with 'v'"
            exit 1
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta for Pro
        id: meta-pro
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com/riverqueue/riverproui
          labels: |
            org.opencontainers.image.source=https://github.com/riverqueue/riverui
            org.opencontainers.image.description="River UI Pro is a web-based user interface for River, with pro features."
            org.opencontainers.image.licenses=MPL-2.0
          # TODO: type=ref are temporary for testing
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build and push to ECR
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.pro
          pull: true
          platforms: ${{ matrix.docker_platform }}
          provenance: true
          labels: ${{ steps.meta-pro.outputs.labels }}
          cache-from: type=registry,ref=${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com/riverqueue/riverproui:cache-${{ env.PLATFORM_PAIR }}
          cache-to: type=registry,mode=max,ref=${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com/riverqueue/riverproui:cache-${{ env.PLATFORM_PAIR }}
          outputs: type=image,name=${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com/riverqueue/riverproui,push-by-digest=true,push=true
          secrets: |
            "riverpro_credential=${{ secrets.RIVERPRO_GO_MOD_CREDENTIAL }}"

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: pro-digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge-riverui:
    name: "Merge manifests: riverui"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}
      REGISTRY: ghcr.io
    needs:
      - build-riverui
    permissions:
      contents: read
      packages: write

    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-oss-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.source=https://github.com/riverqueue/riverui
            org.opencontainers.image.description="River UI is a web-based user interface for River, a fast and reliable background job system."
            org.opencontainers.image.licenses=MPL-2.0
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \
            --annotation "index:org.opencontainers.image.source=https://github.com/riverqueue/riverui" \
            --annotation "index:org.opencontainers.image.description=River UI is a web-based user interface for River, a fast and reliable background job system." \
            --annotation "index:org.opencontainers.image.licenses=MPL-2.0" \
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)

  merge-riverproui:
    name: "Merge manifests: riverproui"
    runs-on: ubuntu-latest
    env:
      ECR_ACCOUNT_ID: ${{ secrets.ECR_CACHE_AWS_ACCOUNT_ID }}
      ECR_ROLE_ARN: ${{ secrets.ECR_CACHE_ROLE_ARN }}
    needs:
      - build-riverproui
    outputs:
      tags: ${{ steps.meta-pro.outputs.tags }}
      digest: ${{ steps.create.outputs.digest }}
    permissions:
      attestations: write
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ECR_ROLE_ARN }}
          aws-region: ${{ env.ECR_REGION }}
          role-session-name: GitHubActions

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.ECR_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: pro-digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta for Pro
        id: meta-pro
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com/riverqueue/riverproui
          labels: |
            org.opencontainers.image.source=https://github.com/riverqueue/riverui
            org.opencontainers.image.description="River UI Pro is a web-based user interface for River, with pro features."
            org.opencontainers.image.licenses=MPL-2.0
          # TODO: type=ref are temporary for testing
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Create manifest list and push to ECR
        working-directory: /tmp/digests
        id: create
        run: |
          docker buildx imagetools create \
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com/riverqueue/riverproui@sha256:%s ' *)
          # Get final digest
          FIRST_TAG=$(jq -r '.tags | .[0]' <<< "$DOCKER_METADATA_OUTPUT_JSON")
          MANIFEST=$(docker buildx imagetools inspect --raw $FIRST_TAG)
          DIGEST=$(printf %s "$MANIFEST" | sha256sum | awk '{print $1}')
          echo "digest=sha256:$DIGEST" >> $GITHUB_OUTPUT

      - name: Generate artifact attestation
        id: attest
        uses: actions/attest-build-provenance@v1
        with:
          push-to-registry: false
          subject-digest: ${{ steps.create.outputs.digest }}
          subject-name: riverqueue.com/riverproui

      - name: Upload attestation bundle
        uses: actions/upload-artifact@v4
        with:
          name: pro-attestation-bundle
          path: ${{ steps.attest.outputs.bundle-path }}
          retention-days: 1

  publish-riverproui:
    name: "Publish Docker image: riverproui"
    runs-on: ubuntu-latest
    env:
      ECR_ACCOUNT_ID: ${{ secrets.ECR_CACHE_AWS_ACCOUNT_ID }}
      ECR_ROLE_ARN: ${{ secrets.ECR_CACHE_ROLE_ARN }}
      REPO_NAME: riverproui
    needs:
      - merge-riverproui
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ECR_ROLE_ARN }}
          aws-region: ${{ env.ECR_REGION }}
          role-session-name: GitHubActions

      - name: Install skopeo
        run: sudo apt-get update && sudo apt-get install -y skopeo jq

      - name: Fetch image from ECR to local OCI dir
        run: |
          PASSWORD=$(aws ecr get-login-password --region ${{ env.ECR_REGION }})
          skopeo login ${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com -u AWS -p $PASSWORD
          skopeo copy --multi-arch all docker://${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com/riverqueue/riverproui@${{ needs.merge-riverproui.outputs.digest }} oci:/tmp/oci

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64

      - name: Download attestation bundle
        uses: actions/download-artifact@v4
        with:
          name: pro-attestation-bundle
          path: /tmp/attestation

      - name: Fetch image from ECR to local OCI dir
        run: |
          PASSWORD=$(aws ecr get-login-password --region ${{ env.ECR_REGION }})
          skopeo login ${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com -u AWS -p $PASSWORD
          skopeo copy --multi-arch all docker://${{ env.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com/riverqueue/riverproui@${{ needs.merge-riverproui.outputs.digest }} oci:/tmp/oci

      - name: Set R2 Credentials
        # The cleanest way I could find to remove remants of the
        # aws-actions/configure-aws-credentials@v4 action and also set up
        # R2-specific values which can't work with the network requests that
        # action makes to try to validate creds.
        run: |
          echo "AWS_DEFAULT_REGION=us-east-2" >> $GITHUB_ENV
          echo "AWS_REGION=us-east-2" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=" >> $GITHUB_ENV

      - name: Sync blobs to R2
        # TODO: temporary for testing
        # if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
        env:
          DOCKER_RELEASE_STORAGE_BUCKET: ${{ vars.DOCKER_RELEASE_STORAGE_BUCKET }}
          ENDPOINT_URL: ${{ secrets.R2_DOCKER_RELEASES_ENDPOINT_URL }}
        run: |
          aws s3 cp /tmp/oci/blobs/sha256/ s3://$DOCKER_RELEASE_STORAGE_BUCKET/$REPO_NAME/blobs/sha256/ --endpoint-url $ENDPOINT_URL --region auto --recursive

      - name: Upload manifest by digest
        # TODO: temporary for testing
        # if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
        env:
          DOCKER_RELEASE_STORAGE_BUCKET: ${{ vars.DOCKER_RELEASE_STORAGE_BUCKET }}
          ENDPOINT_URL: ${{ secrets.R2_DOCKER_RELEASES_ENDPOINT_URL }}
        run: |
          MANIFEST_DIGEST=$(sha256sum /tmp/oci/index.json | awk '{print $1}')
          aws s3 cp /tmp/oci/index.json s3://$DOCKER_RELEASE_STORAGE_BUCKET/$REPO_NAME/manifests/sha256:$MANIFEST_DIGEST --endpoint-url $ENDPOINT_URL --region auto --content-type "application/vnd.docker.distribution.manifest.list.v2+json"

      - name: Upload tagged manifests as symlinks
        # TODO: temporary for testing
        # if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
        env:
          DOCKER_RELEASE_STORAGE_BUCKET: ${{ vars.DOCKER_RELEASE_STORAGE_BUCKET }}
          ENDPOINT_URL: ${{ secrets.R2_DOCKER_RELEASES_ENDPOINT_URL }}
        run: |
          MANIFEST_DIGEST=$(sha256sum /tmp/oci/index.json | awk '{print $1}')
          echo '${{ needs.merge-riverproui.outputs.tags }}' > tags.txt
          while IFS= read -r TAG; do
            if [ -n "$TAG" ]; then
              SHORT_TAG="${TAG#riverqueue.com/riverproui:}"
              echo -n "" | aws s3 cp - s3://$DOCKER_RELEASE_STORAGE_BUCKET/$REPO_NAME/manifests/$SHORT_TAG --endpoint-url $ENDPOINT_URL --region auto --metadata "X-Serverless-Registry-Symlink=sha256:$MANIFEST_DIGEST" --content-type "application/octet-stream"
            fi
          done < tags.txt

      - name: Upload referrers (attestation)
        env:
          DOCKER_RELEASE_STORAGE_BUCKET: ${{ vars.DOCKER_RELEASE_STORAGE_BUCKET }}
          ENDPOINT_URL: ${{ secrets.R2_DOCKER_RELEASES_ENDPOINT_URL }}
        run: |
          MANIFEST_DIGEST=$(sha256sum /tmp/oci/index.json | awk '{print $1}')
          ATTESTATION_FILE=$(ls /tmp/attestation/* | head -1)
          aws s3 cp $ATTESTATION_FILE s3://$DOCKER_RELEASE_STORAGE_BUCKET/$REPO_NAME/referrers/sha256:$MANIFEST_DIGEST --endpoint-url $ENDPOINT_URL --region auto --content-type "application/vnd.oci.image.index.v1+json"
